/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#0a0814",
        sidebar: "#0c0a18",
        surface: "#161222",
        surface2: "#120f20",
        raised: "#1a1530",
        input: "#100d1c",
        hover: "#181327",
        line: "#251f3a",
        line2: "#2b2442",
        linedim: "#1f1930",
        accent: "#a24bff",
        accent2: "#8b45ff",
        magenta: "#d846c9",
        accentsoft: "#c9a6ff",
        ink: "#ece9f6",
        ink2: "#f4f1fc",
        muted: "#9890b6",
        muted2: "#8d86ab",
        faint: "#6f688c",
        faint2: "#6b6390",
        success: "#35d9a0",
        danger: "#ff5470",
        danger2: "#ff7a92",
        warning: "#f5b544",
        discord: "#5865f2",
      },
      fontFamily: {
        sora: ["Sora", "sans-serif"],
        jakarta: ['"Plus Jakarta Sans"', "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
      },
      boxShadow: {
        card: "0 18px 34px -30px rgba(0,0,0,.9)",
        glow: "0 12px 26px -12px rgba(150,70,240,.8)",
      },
      keyframes: {
        fIn: { from: { transform: "translateY(8px)", opacity: "0" }, to: { transform: "none", opacity: "1" } },
        mIn: { from: { transform: "translateY(12px) scale(.98)", opacity: "0" }, to: { transform: "none", opacity: "1" } },
        tIn: { from: { transform: "translateY(10px)", opacity: "0" }, to: { transform: "none", opacity: "1" } },
        blob: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "50%": { transform: "translate(30px,-40px) scale(1.1)" } },
      },
      animation: {
        fIn: "fIn .25s ease",
        mIn: "mIn .3s ease",
        tIn: "tIn .22s ease",
        blob: "blob 14s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
